version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: auth-phonebook-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8899
      POSTGRES_DB: auth_phonebook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: auth-phonebook-app
    environment:
      DATABASE_URL: postgresql://postgres:8899@db:5432/auth_phonebook_db
      PORT: 3000
      JWT_SECRET: supersecretkey
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data: